# -*- coding: utf-8 -*-
from odoo import models, fields, api


class AccountMove(models.Model):
    _inherit = 'account.move'

    l10n_mx_edi_imported_from_xml = fields.Boolean(
        string='Imported from XML',
        default=False,
        readonly=True,
        help='If this field is active, the CFDI was imported from its XML file.')
    l10n_mx_edi_sign_required = fields.Boolean(
        string='Sign Invoice?',
        default=True,
        store=True,
        states={'draft': [('readonly', False)]},
        help='If this field is active, the CFDI will be generated for this invoice.')
    l10n_mx_edi_external_reference = fields.Char(
        string='External Reference',
        help='External Invoice Reference comes normally in the PDF, it was generated by the'
        ' External Partner who signed the invoice.', copy=False)
    l10n_mx_edi_usage = fields.Selection(selection_add=[('S01', 'No tax effects')])

    @api.depends('move_type', 'company_id')
    def _compute_l10n_mx_edi_cfdi_request(self):
        for move in self:
            if move.country_code != 'MX' or (move.l10n_mx_edi_sign_required is False and move.state != 'posted'):
                move.l10n_mx_edi_cfdi_request = False
            elif move.move_type == 'out_invoice':
                move.l10n_mx_edi_cfdi_request = 'on_invoice'
            elif move.move_type == 'out_refund':
                move.l10n_mx_edi_cfdi_request = 'on_refund'
            elif move.payment_id or move.statement_line_id:
                move.l10n_mx_edi_cfdi_request = 'on_payment'
            else:
                move.l10n_mx_edi_cfdi_request = False

    def _post(self, soft=True):
        # OVERRIDE
        to_post = super()._post(soft=soft)

        for move in self:
            if move.l10n_mx_edi_sign_required is False:
                move._compute_l10n_mx_edi_cfdi_request()

        return to_post


class AccountMoveLine(models.Model):
    _inherit = "account.move.line"

    @api.onchange('product_id')
    def _onchange_product_id(self):
        if not self.move_id.l10n_mx_edi_imported_from_xml:
            super(AccountMoveLine, self)._onchange_product_id()

